project:
  type: website
  output-dir: public

website:
  title: "Sabrina Eisenberg"
  twitter-card: true
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Presentations.qmd
        text: Publications/CV

      

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

