---
title: "Publications/CV"
---

[Click here for a full version of my updated CV](SabrinaEisenbergCV.pdf)

## Poster Presentations

Eisenberg, S. Coy, A. (February 2022). [Attachment and laypersons' views of healthy relationships.](Attachment.qmd)*Poster presentation at Society for Personality and Social Psychology, Annual Conference.*

Eisenberg, S. Michaels, J. (February 2022). [Belongingness and global thinking contribute to spiritual people's ability to avoid meaning violation and distress during the COVID-19 pandemic.](MeaningMaking.qmd) *Poster presentation at Society for Personality and Social Psychology, Psychology of Religion and Spirituality Pre-Conference, Virtual*

Eisenberg, S. & Pauletti, R. (February 2021). Narcissism, attraction, and self-esteem: Comparing agentic and communal subtypes. *Poster presentation at Society for Personality and Social Psychology, Virtual Conference.*

## Magazine Articles

### Psychedelic Science Review

[MDMA, PTSD, and Potentially Overlooked Positive Outcomes](https://psychedelicreview.com/mdma-ptsd-and-potentially-overlooked-positive-outcomes/)

[What is the Default Mode Network?](https://psychedelicreview.com/what-is-the-default-mode-network/)

[What is the Mystical Experience Questionnaire?](https://psychedelicreview.com/what-is-the-mystical-experience-questionnaire/)

[Psychedelic Science 101: What are Psychedelic Drugs?](https://psychedelicreview.com/psychedelic-science-101-what-are-psychedelic-drugs/)

[Fear of Death Impacts Quality of Life - How Psychedelics Can Help](https://psychedelicreview.com/fear-of-death-impacts-quality-of-life-how-psychedelics-can-help/)
